// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BarRatingController from "./bar_rating_controller.js"
application.register("bar-rating", BarRatingController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller.js"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import CountingController from "./counting_controller.js"
application.register("counting", CountingController)

import FlatpickrController from "./flatpickr_controller.js"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import InsertInListController from "./insert_in_list_controller.js"
application.register("insert-in-list", InsertInListController)

import MapController from "./map_controller.js"
application.register("map", MapController)
