meta_product_name: "FOODbreaker"
meta_title: "FOODBreaker - First social dinning network in France. Join us to meet pepole around fodd events!"
meta_description: "First socail dinning app allowing expatriates and new comers to meet people around food events"
meta_image: "Mirrodles.png" # should exist in `app/assets/images/`
#twitter_account: "@product_twitter_account"   # required for Twitter Cards
